// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/kafka"
)

type KafkaSaramaClientPool struct {
	AcquireStub        func(context.Context) (kafka.SaramaClient, error)
	acquireMutex       sync.RWMutex
	acquireArgsForCall []struct {
		arg1 context.Context
	}
	acquireReturns struct {
		result1 kafka.SaramaClient
		result2 error
	}
	acquireReturnsOnCall map[int]struct {
		result1 kafka.SaramaClient
		result2 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	ReleaseStub        func(kafka.SaramaClient, bool)
	releaseMutex       sync.RWMutex
	releaseArgsForCall []struct {
		arg1 kafka.SaramaClient
		arg2 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *KafkaSaramaClientPool) Acquire(arg1 context.Context) (kafka.SaramaClient, error) {
	fake.acquireMutex.Lock()
	ret, specificReturn := fake.acquireReturnsOnCall[len(fake.acquireArgsForCall)]
	fake.acquireArgsForCall = append(fake.acquireArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.AcquireStub
	fakeReturns := fake.acquireReturns
	fake.recordInvocation("Acquire", []interface{}{arg1})
	fake.acquireMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *KafkaSaramaClientPool) AcquireCallCount() int {
	fake.acquireMutex.RLock()
	defer fake.acquireMutex.RUnlock()
	return len(fake.acquireArgsForCall)
}

func (fake *KafkaSaramaClientPool) AcquireCalls(stub func(context.Context) (kafka.SaramaClient, error)) {
	fake.acquireMutex.Lock()
	defer fake.acquireMutex.Unlock()
	fake.AcquireStub = stub
}

func (fake *KafkaSaramaClientPool) AcquireArgsForCall(i int) context.Context {
	fake.acquireMutex.RLock()
	defer fake.acquireMutex.RUnlock()
	argsForCall := fake.acquireArgsForCall[i]
	return argsForCall.arg1
}

func (fake *KafkaSaramaClientPool) AcquireReturns(result1 kafka.SaramaClient, result2 error) {
	fake.acquireMutex.Lock()
	defer fake.acquireMutex.Unlock()
	fake.AcquireStub = nil
	fake.acquireReturns = struct {
		result1 kafka.SaramaClient
		result2 error
	}{result1, result2}
}

func (fake *KafkaSaramaClientPool) AcquireReturnsOnCall(i int, result1 kafka.SaramaClient, result2 error) {
	fake.acquireMutex.Lock()
	defer fake.acquireMutex.Unlock()
	fake.AcquireStub = nil
	if fake.acquireReturnsOnCall == nil {
		fake.acquireReturnsOnCall = make(map[int]struct {
			result1 kafka.SaramaClient
			result2 error
		})
	}
	fake.acquireReturnsOnCall[i] = struct {
		result1 kafka.SaramaClient
		result2 error
	}{result1, result2}
}

func (fake *KafkaSaramaClientPool) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KafkaSaramaClientPool) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *KafkaSaramaClientPool) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *KafkaSaramaClientPool) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *KafkaSaramaClientPool) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KafkaSaramaClientPool) Release(arg1 kafka.SaramaClient, arg2 bool) {
	fake.releaseMutex.Lock()
	fake.releaseArgsForCall = append(fake.releaseArgsForCall, struct {
		arg1 kafka.SaramaClient
		arg2 bool
	}{arg1, arg2})
	stub := fake.ReleaseStub
	fake.recordInvocation("Release", []interface{}{arg1, arg2})
	fake.releaseMutex.Unlock()
	if stub != nil {
		fake.ReleaseStub(arg1, arg2)
	}
}

func (fake *KafkaSaramaClientPool) ReleaseCallCount() int {
	fake.releaseMutex.RLock()
	defer fake.releaseMutex.RUnlock()
	return len(fake.releaseArgsForCall)
}

func (fake *KafkaSaramaClientPool) ReleaseCalls(stub func(kafka.SaramaClient, bool)) {
	fake.releaseMutex.Lock()
	defer fake.releaseMutex.Unlock()
	fake.ReleaseStub = stub
}

func (fake *KafkaSaramaClientPool) ReleaseArgsForCall(i int) (kafka.SaramaClient, bool) {
	fake.releaseMutex.RLock()
	defer fake.releaseMutex.RUnlock()
	argsForCall := fake.releaseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *KafkaSaramaClientPool) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *KafkaSaramaClientPool) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kafka.SaramaClientPool = new(KafkaSaramaClientPool)
