// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"
	"time"

	"github.com/bborbe/kafka"
)

type KafkaMetrics struct {
	CurrentOffsetStub        func(kafka.Topic, kafka.Partition, kafka.Offset)
	currentOffsetMutex       sync.RWMutex
	currentOffsetArgsForCall []struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
		arg3 kafka.Offset
	}
	HighWaterMarkOffsetStub        func(kafka.Topic, kafka.Partition, kafka.Offset)
	highWaterMarkOffsetMutex       sync.RWMutex
	highWaterMarkOffsetArgsForCall []struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
		arg3 kafka.Offset
	}
	MessageHandlerDurationMeasureStub        func(kafka.Topic, kafka.Partition, time.Duration)
	messageHandlerDurationMeasureMutex       sync.RWMutex
	messageHandlerDurationMeasureArgsForCall []struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
		arg3 time.Duration
	}
	MessageHandlerFailureCounterIncStub        func(kafka.Topic, kafka.Partition)
	messageHandlerFailureCounterIncMutex       sync.RWMutex
	messageHandlerFailureCounterIncArgsForCall []struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
	}
	MessageHandlerSuccessCounterIncStub        func(kafka.Topic, kafka.Partition)
	messageHandlerSuccessCounterIncMutex       sync.RWMutex
	messageHandlerSuccessCounterIncArgsForCall []struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
	}
	MessageHandlerTotalCounterIncStub        func(kafka.Topic, kafka.Partition)
	messageHandlerTotalCounterIncMutex       sync.RWMutex
	messageHandlerTotalCounterIncArgsForCall []struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *KafkaMetrics) CurrentOffset(arg1 kafka.Topic, arg2 kafka.Partition, arg3 kafka.Offset) {
	fake.currentOffsetMutex.Lock()
	fake.currentOffsetArgsForCall = append(fake.currentOffsetArgsForCall, struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
		arg3 kafka.Offset
	}{arg1, arg2, arg3})
	stub := fake.CurrentOffsetStub
	fake.recordInvocation("CurrentOffset", []interface{}{arg1, arg2, arg3})
	fake.currentOffsetMutex.Unlock()
	if stub != nil {
		fake.CurrentOffsetStub(arg1, arg2, arg3)
	}
}

func (fake *KafkaMetrics) CurrentOffsetCallCount() int {
	fake.currentOffsetMutex.RLock()
	defer fake.currentOffsetMutex.RUnlock()
	return len(fake.currentOffsetArgsForCall)
}

func (fake *KafkaMetrics) CurrentOffsetCalls(stub func(kafka.Topic, kafka.Partition, kafka.Offset)) {
	fake.currentOffsetMutex.Lock()
	defer fake.currentOffsetMutex.Unlock()
	fake.CurrentOffsetStub = stub
}

func (fake *KafkaMetrics) CurrentOffsetArgsForCall(i int) (kafka.Topic, kafka.Partition, kafka.Offset) {
	fake.currentOffsetMutex.RLock()
	defer fake.currentOffsetMutex.RUnlock()
	argsForCall := fake.currentOffsetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KafkaMetrics) HighWaterMarkOffset(arg1 kafka.Topic, arg2 kafka.Partition, arg3 kafka.Offset) {
	fake.highWaterMarkOffsetMutex.Lock()
	fake.highWaterMarkOffsetArgsForCall = append(fake.highWaterMarkOffsetArgsForCall, struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
		arg3 kafka.Offset
	}{arg1, arg2, arg3})
	stub := fake.HighWaterMarkOffsetStub
	fake.recordInvocation("HighWaterMarkOffset", []interface{}{arg1, arg2, arg3})
	fake.highWaterMarkOffsetMutex.Unlock()
	if stub != nil {
		fake.HighWaterMarkOffsetStub(arg1, arg2, arg3)
	}
}

func (fake *KafkaMetrics) HighWaterMarkOffsetCallCount() int {
	fake.highWaterMarkOffsetMutex.RLock()
	defer fake.highWaterMarkOffsetMutex.RUnlock()
	return len(fake.highWaterMarkOffsetArgsForCall)
}

func (fake *KafkaMetrics) HighWaterMarkOffsetCalls(stub func(kafka.Topic, kafka.Partition, kafka.Offset)) {
	fake.highWaterMarkOffsetMutex.Lock()
	defer fake.highWaterMarkOffsetMutex.Unlock()
	fake.HighWaterMarkOffsetStub = stub
}

func (fake *KafkaMetrics) HighWaterMarkOffsetArgsForCall(i int) (kafka.Topic, kafka.Partition, kafka.Offset) {
	fake.highWaterMarkOffsetMutex.RLock()
	defer fake.highWaterMarkOffsetMutex.RUnlock()
	argsForCall := fake.highWaterMarkOffsetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KafkaMetrics) MessageHandlerDurationMeasure(arg1 kafka.Topic, arg2 kafka.Partition, arg3 time.Duration) {
	fake.messageHandlerDurationMeasureMutex.Lock()
	fake.messageHandlerDurationMeasureArgsForCall = append(fake.messageHandlerDurationMeasureArgsForCall, struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
		arg3 time.Duration
	}{arg1, arg2, arg3})
	stub := fake.MessageHandlerDurationMeasureStub
	fake.recordInvocation("MessageHandlerDurationMeasure", []interface{}{arg1, arg2, arg3})
	fake.messageHandlerDurationMeasureMutex.Unlock()
	if stub != nil {
		fake.MessageHandlerDurationMeasureStub(arg1, arg2, arg3)
	}
}

func (fake *KafkaMetrics) MessageHandlerDurationMeasureCallCount() int {
	fake.messageHandlerDurationMeasureMutex.RLock()
	defer fake.messageHandlerDurationMeasureMutex.RUnlock()
	return len(fake.messageHandlerDurationMeasureArgsForCall)
}

func (fake *KafkaMetrics) MessageHandlerDurationMeasureCalls(stub func(kafka.Topic, kafka.Partition, time.Duration)) {
	fake.messageHandlerDurationMeasureMutex.Lock()
	defer fake.messageHandlerDurationMeasureMutex.Unlock()
	fake.MessageHandlerDurationMeasureStub = stub
}

func (fake *KafkaMetrics) MessageHandlerDurationMeasureArgsForCall(i int) (kafka.Topic, kafka.Partition, time.Duration) {
	fake.messageHandlerDurationMeasureMutex.RLock()
	defer fake.messageHandlerDurationMeasureMutex.RUnlock()
	argsForCall := fake.messageHandlerDurationMeasureArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KafkaMetrics) MessageHandlerFailureCounterInc(arg1 kafka.Topic, arg2 kafka.Partition) {
	fake.messageHandlerFailureCounterIncMutex.Lock()
	fake.messageHandlerFailureCounterIncArgsForCall = append(fake.messageHandlerFailureCounterIncArgsForCall, struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
	}{arg1, arg2})
	stub := fake.MessageHandlerFailureCounterIncStub
	fake.recordInvocation("MessageHandlerFailureCounterInc", []interface{}{arg1, arg2})
	fake.messageHandlerFailureCounterIncMutex.Unlock()
	if stub != nil {
		fake.MessageHandlerFailureCounterIncStub(arg1, arg2)
	}
}

func (fake *KafkaMetrics) MessageHandlerFailureCounterIncCallCount() int {
	fake.messageHandlerFailureCounterIncMutex.RLock()
	defer fake.messageHandlerFailureCounterIncMutex.RUnlock()
	return len(fake.messageHandlerFailureCounterIncArgsForCall)
}

func (fake *KafkaMetrics) MessageHandlerFailureCounterIncCalls(stub func(kafka.Topic, kafka.Partition)) {
	fake.messageHandlerFailureCounterIncMutex.Lock()
	defer fake.messageHandlerFailureCounterIncMutex.Unlock()
	fake.MessageHandlerFailureCounterIncStub = stub
}

func (fake *KafkaMetrics) MessageHandlerFailureCounterIncArgsForCall(i int) (kafka.Topic, kafka.Partition) {
	fake.messageHandlerFailureCounterIncMutex.RLock()
	defer fake.messageHandlerFailureCounterIncMutex.RUnlock()
	argsForCall := fake.messageHandlerFailureCounterIncArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *KafkaMetrics) MessageHandlerSuccessCounterInc(arg1 kafka.Topic, arg2 kafka.Partition) {
	fake.messageHandlerSuccessCounterIncMutex.Lock()
	fake.messageHandlerSuccessCounterIncArgsForCall = append(fake.messageHandlerSuccessCounterIncArgsForCall, struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
	}{arg1, arg2})
	stub := fake.MessageHandlerSuccessCounterIncStub
	fake.recordInvocation("MessageHandlerSuccessCounterInc", []interface{}{arg1, arg2})
	fake.messageHandlerSuccessCounterIncMutex.Unlock()
	if stub != nil {
		fake.MessageHandlerSuccessCounterIncStub(arg1, arg2)
	}
}

func (fake *KafkaMetrics) MessageHandlerSuccessCounterIncCallCount() int {
	fake.messageHandlerSuccessCounterIncMutex.RLock()
	defer fake.messageHandlerSuccessCounterIncMutex.RUnlock()
	return len(fake.messageHandlerSuccessCounterIncArgsForCall)
}

func (fake *KafkaMetrics) MessageHandlerSuccessCounterIncCalls(stub func(kafka.Topic, kafka.Partition)) {
	fake.messageHandlerSuccessCounterIncMutex.Lock()
	defer fake.messageHandlerSuccessCounterIncMutex.Unlock()
	fake.MessageHandlerSuccessCounterIncStub = stub
}

func (fake *KafkaMetrics) MessageHandlerSuccessCounterIncArgsForCall(i int) (kafka.Topic, kafka.Partition) {
	fake.messageHandlerSuccessCounterIncMutex.RLock()
	defer fake.messageHandlerSuccessCounterIncMutex.RUnlock()
	argsForCall := fake.messageHandlerSuccessCounterIncArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *KafkaMetrics) MessageHandlerTotalCounterInc(arg1 kafka.Topic, arg2 kafka.Partition) {
	fake.messageHandlerTotalCounterIncMutex.Lock()
	fake.messageHandlerTotalCounterIncArgsForCall = append(fake.messageHandlerTotalCounterIncArgsForCall, struct {
		arg1 kafka.Topic
		arg2 kafka.Partition
	}{arg1, arg2})
	stub := fake.MessageHandlerTotalCounterIncStub
	fake.recordInvocation("MessageHandlerTotalCounterInc", []interface{}{arg1, arg2})
	fake.messageHandlerTotalCounterIncMutex.Unlock()
	if stub != nil {
		fake.MessageHandlerTotalCounterIncStub(arg1, arg2)
	}
}

func (fake *KafkaMetrics) MessageHandlerTotalCounterIncCallCount() int {
	fake.messageHandlerTotalCounterIncMutex.RLock()
	defer fake.messageHandlerTotalCounterIncMutex.RUnlock()
	return len(fake.messageHandlerTotalCounterIncArgsForCall)
}

func (fake *KafkaMetrics) MessageHandlerTotalCounterIncCalls(stub func(kafka.Topic, kafka.Partition)) {
	fake.messageHandlerTotalCounterIncMutex.Lock()
	defer fake.messageHandlerTotalCounterIncMutex.Unlock()
	fake.MessageHandlerTotalCounterIncStub = stub
}

func (fake *KafkaMetrics) MessageHandlerTotalCounterIncArgsForCall(i int) (kafka.Topic, kafka.Partition) {
	fake.messageHandlerTotalCounterIncMutex.RLock()
	defer fake.messageHandlerTotalCounterIncMutex.RUnlock()
	argsForCall := fake.messageHandlerTotalCounterIncArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *KafkaMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.currentOffsetMutex.RLock()
	defer fake.currentOffsetMutex.RUnlock()
	fake.highWaterMarkOffsetMutex.RLock()
	defer fake.highWaterMarkOffsetMutex.RUnlock()
	fake.messageHandlerDurationMeasureMutex.RLock()
	defer fake.messageHandlerDurationMeasureMutex.RUnlock()
	fake.messageHandlerFailureCounterIncMutex.RLock()
	defer fake.messageHandlerFailureCounterIncMutex.RUnlock()
	fake.messageHandlerSuccessCounterIncMutex.RLock()
	defer fake.messageHandlerSuccessCounterIncMutex.RUnlock()
	fake.messageHandlerTotalCounterIncMutex.RLock()
	defer fake.messageHandlerTotalCounterIncMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *KafkaMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kafka.Metrics = new(KafkaMetrics)
