// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/kafka"
)

type KafkaOffsetManager struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	FallbackOffsetStub        func() kafka.Offset
	fallbackOffsetMutex       sync.RWMutex
	fallbackOffsetArgsForCall []struct {
	}
	fallbackOffsetReturns struct {
		result1 kafka.Offset
	}
	fallbackOffsetReturnsOnCall map[int]struct {
		result1 kafka.Offset
	}
	InitialOffsetStub        func() kafka.Offset
	initialOffsetMutex       sync.RWMutex
	initialOffsetArgsForCall []struct {
	}
	initialOffsetReturns struct {
		result1 kafka.Offset
	}
	initialOffsetReturnsOnCall map[int]struct {
		result1 kafka.Offset
	}
	MarkOffsetStub        func(context.Context, kafka.Topic, kafka.Partition, kafka.Offset) error
	markOffsetMutex       sync.RWMutex
	markOffsetArgsForCall []struct {
		arg1 context.Context
		arg2 kafka.Topic
		arg3 kafka.Partition
		arg4 kafka.Offset
	}
	markOffsetReturns struct {
		result1 error
	}
	markOffsetReturnsOnCall map[int]struct {
		result1 error
	}
	NextOffsetStub        func(context.Context, kafka.Topic, kafka.Partition) (kafka.Offset, error)
	nextOffsetMutex       sync.RWMutex
	nextOffsetArgsForCall []struct {
		arg1 context.Context
		arg2 kafka.Topic
		arg3 kafka.Partition
	}
	nextOffsetReturns struct {
		result1 kafka.Offset
		result2 error
	}
	nextOffsetReturnsOnCall map[int]struct {
		result1 kafka.Offset
		result2 error
	}
	ResetOffsetStub        func(context.Context, kafka.Topic, kafka.Partition, kafka.Offset) error
	resetOffsetMutex       sync.RWMutex
	resetOffsetArgsForCall []struct {
		arg1 context.Context
		arg2 kafka.Topic
		arg3 kafka.Partition
		arg4 kafka.Offset
	}
	resetOffsetReturns struct {
		result1 error
	}
	resetOffsetReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *KafkaOffsetManager) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KafkaOffsetManager) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *KafkaOffsetManager) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *KafkaOffsetManager) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *KafkaOffsetManager) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KafkaOffsetManager) FallbackOffset() kafka.Offset {
	fake.fallbackOffsetMutex.Lock()
	ret, specificReturn := fake.fallbackOffsetReturnsOnCall[len(fake.fallbackOffsetArgsForCall)]
	fake.fallbackOffsetArgsForCall = append(fake.fallbackOffsetArgsForCall, struct {
	}{})
	stub := fake.FallbackOffsetStub
	fakeReturns := fake.fallbackOffsetReturns
	fake.recordInvocation("FallbackOffset", []interface{}{})
	fake.fallbackOffsetMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KafkaOffsetManager) FallbackOffsetCallCount() int {
	fake.fallbackOffsetMutex.RLock()
	defer fake.fallbackOffsetMutex.RUnlock()
	return len(fake.fallbackOffsetArgsForCall)
}

func (fake *KafkaOffsetManager) FallbackOffsetCalls(stub func() kafka.Offset) {
	fake.fallbackOffsetMutex.Lock()
	defer fake.fallbackOffsetMutex.Unlock()
	fake.FallbackOffsetStub = stub
}

func (fake *KafkaOffsetManager) FallbackOffsetReturns(result1 kafka.Offset) {
	fake.fallbackOffsetMutex.Lock()
	defer fake.fallbackOffsetMutex.Unlock()
	fake.FallbackOffsetStub = nil
	fake.fallbackOffsetReturns = struct {
		result1 kafka.Offset
	}{result1}
}

func (fake *KafkaOffsetManager) FallbackOffsetReturnsOnCall(i int, result1 kafka.Offset) {
	fake.fallbackOffsetMutex.Lock()
	defer fake.fallbackOffsetMutex.Unlock()
	fake.FallbackOffsetStub = nil
	if fake.fallbackOffsetReturnsOnCall == nil {
		fake.fallbackOffsetReturnsOnCall = make(map[int]struct {
			result1 kafka.Offset
		})
	}
	fake.fallbackOffsetReturnsOnCall[i] = struct {
		result1 kafka.Offset
	}{result1}
}

func (fake *KafkaOffsetManager) InitialOffset() kafka.Offset {
	fake.initialOffsetMutex.Lock()
	ret, specificReturn := fake.initialOffsetReturnsOnCall[len(fake.initialOffsetArgsForCall)]
	fake.initialOffsetArgsForCall = append(fake.initialOffsetArgsForCall, struct {
	}{})
	stub := fake.InitialOffsetStub
	fakeReturns := fake.initialOffsetReturns
	fake.recordInvocation("InitialOffset", []interface{}{})
	fake.initialOffsetMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KafkaOffsetManager) InitialOffsetCallCount() int {
	fake.initialOffsetMutex.RLock()
	defer fake.initialOffsetMutex.RUnlock()
	return len(fake.initialOffsetArgsForCall)
}

func (fake *KafkaOffsetManager) InitialOffsetCalls(stub func() kafka.Offset) {
	fake.initialOffsetMutex.Lock()
	defer fake.initialOffsetMutex.Unlock()
	fake.InitialOffsetStub = stub
}

func (fake *KafkaOffsetManager) InitialOffsetReturns(result1 kafka.Offset) {
	fake.initialOffsetMutex.Lock()
	defer fake.initialOffsetMutex.Unlock()
	fake.InitialOffsetStub = nil
	fake.initialOffsetReturns = struct {
		result1 kafka.Offset
	}{result1}
}

func (fake *KafkaOffsetManager) InitialOffsetReturnsOnCall(i int, result1 kafka.Offset) {
	fake.initialOffsetMutex.Lock()
	defer fake.initialOffsetMutex.Unlock()
	fake.InitialOffsetStub = nil
	if fake.initialOffsetReturnsOnCall == nil {
		fake.initialOffsetReturnsOnCall = make(map[int]struct {
			result1 kafka.Offset
		})
	}
	fake.initialOffsetReturnsOnCall[i] = struct {
		result1 kafka.Offset
	}{result1}
}

func (fake *KafkaOffsetManager) MarkOffset(arg1 context.Context, arg2 kafka.Topic, arg3 kafka.Partition, arg4 kafka.Offset) error {
	fake.markOffsetMutex.Lock()
	ret, specificReturn := fake.markOffsetReturnsOnCall[len(fake.markOffsetArgsForCall)]
	fake.markOffsetArgsForCall = append(fake.markOffsetArgsForCall, struct {
		arg1 context.Context
		arg2 kafka.Topic
		arg3 kafka.Partition
		arg4 kafka.Offset
	}{arg1, arg2, arg3, arg4})
	stub := fake.MarkOffsetStub
	fakeReturns := fake.markOffsetReturns
	fake.recordInvocation("MarkOffset", []interface{}{arg1, arg2, arg3, arg4})
	fake.markOffsetMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KafkaOffsetManager) MarkOffsetCallCount() int {
	fake.markOffsetMutex.RLock()
	defer fake.markOffsetMutex.RUnlock()
	return len(fake.markOffsetArgsForCall)
}

func (fake *KafkaOffsetManager) MarkOffsetCalls(stub func(context.Context, kafka.Topic, kafka.Partition, kafka.Offset) error) {
	fake.markOffsetMutex.Lock()
	defer fake.markOffsetMutex.Unlock()
	fake.MarkOffsetStub = stub
}

func (fake *KafkaOffsetManager) MarkOffsetArgsForCall(i int) (context.Context, kafka.Topic, kafka.Partition, kafka.Offset) {
	fake.markOffsetMutex.RLock()
	defer fake.markOffsetMutex.RUnlock()
	argsForCall := fake.markOffsetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *KafkaOffsetManager) MarkOffsetReturns(result1 error) {
	fake.markOffsetMutex.Lock()
	defer fake.markOffsetMutex.Unlock()
	fake.MarkOffsetStub = nil
	fake.markOffsetReturns = struct {
		result1 error
	}{result1}
}

func (fake *KafkaOffsetManager) MarkOffsetReturnsOnCall(i int, result1 error) {
	fake.markOffsetMutex.Lock()
	defer fake.markOffsetMutex.Unlock()
	fake.MarkOffsetStub = nil
	if fake.markOffsetReturnsOnCall == nil {
		fake.markOffsetReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.markOffsetReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KafkaOffsetManager) NextOffset(arg1 context.Context, arg2 kafka.Topic, arg3 kafka.Partition) (kafka.Offset, error) {
	fake.nextOffsetMutex.Lock()
	ret, specificReturn := fake.nextOffsetReturnsOnCall[len(fake.nextOffsetArgsForCall)]
	fake.nextOffsetArgsForCall = append(fake.nextOffsetArgsForCall, struct {
		arg1 context.Context
		arg2 kafka.Topic
		arg3 kafka.Partition
	}{arg1, arg2, arg3})
	stub := fake.NextOffsetStub
	fakeReturns := fake.nextOffsetReturns
	fake.recordInvocation("NextOffset", []interface{}{arg1, arg2, arg3})
	fake.nextOffsetMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *KafkaOffsetManager) NextOffsetCallCount() int {
	fake.nextOffsetMutex.RLock()
	defer fake.nextOffsetMutex.RUnlock()
	return len(fake.nextOffsetArgsForCall)
}

func (fake *KafkaOffsetManager) NextOffsetCalls(stub func(context.Context, kafka.Topic, kafka.Partition) (kafka.Offset, error)) {
	fake.nextOffsetMutex.Lock()
	defer fake.nextOffsetMutex.Unlock()
	fake.NextOffsetStub = stub
}

func (fake *KafkaOffsetManager) NextOffsetArgsForCall(i int) (context.Context, kafka.Topic, kafka.Partition) {
	fake.nextOffsetMutex.RLock()
	defer fake.nextOffsetMutex.RUnlock()
	argsForCall := fake.nextOffsetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *KafkaOffsetManager) NextOffsetReturns(result1 kafka.Offset, result2 error) {
	fake.nextOffsetMutex.Lock()
	defer fake.nextOffsetMutex.Unlock()
	fake.NextOffsetStub = nil
	fake.nextOffsetReturns = struct {
		result1 kafka.Offset
		result2 error
	}{result1, result2}
}

func (fake *KafkaOffsetManager) NextOffsetReturnsOnCall(i int, result1 kafka.Offset, result2 error) {
	fake.nextOffsetMutex.Lock()
	defer fake.nextOffsetMutex.Unlock()
	fake.NextOffsetStub = nil
	if fake.nextOffsetReturnsOnCall == nil {
		fake.nextOffsetReturnsOnCall = make(map[int]struct {
			result1 kafka.Offset
			result2 error
		})
	}
	fake.nextOffsetReturnsOnCall[i] = struct {
		result1 kafka.Offset
		result2 error
	}{result1, result2}
}

func (fake *KafkaOffsetManager) ResetOffset(arg1 context.Context, arg2 kafka.Topic, arg3 kafka.Partition, arg4 kafka.Offset) error {
	fake.resetOffsetMutex.Lock()
	ret, specificReturn := fake.resetOffsetReturnsOnCall[len(fake.resetOffsetArgsForCall)]
	fake.resetOffsetArgsForCall = append(fake.resetOffsetArgsForCall, struct {
		arg1 context.Context
		arg2 kafka.Topic
		arg3 kafka.Partition
		arg4 kafka.Offset
	}{arg1, arg2, arg3, arg4})
	stub := fake.ResetOffsetStub
	fakeReturns := fake.resetOffsetReturns
	fake.recordInvocation("ResetOffset", []interface{}{arg1, arg2, arg3, arg4})
	fake.resetOffsetMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *KafkaOffsetManager) ResetOffsetCallCount() int {
	fake.resetOffsetMutex.RLock()
	defer fake.resetOffsetMutex.RUnlock()
	return len(fake.resetOffsetArgsForCall)
}

func (fake *KafkaOffsetManager) ResetOffsetCalls(stub func(context.Context, kafka.Topic, kafka.Partition, kafka.Offset) error) {
	fake.resetOffsetMutex.Lock()
	defer fake.resetOffsetMutex.Unlock()
	fake.ResetOffsetStub = stub
}

func (fake *KafkaOffsetManager) ResetOffsetArgsForCall(i int) (context.Context, kafka.Topic, kafka.Partition, kafka.Offset) {
	fake.resetOffsetMutex.RLock()
	defer fake.resetOffsetMutex.RUnlock()
	argsForCall := fake.resetOffsetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *KafkaOffsetManager) ResetOffsetReturns(result1 error) {
	fake.resetOffsetMutex.Lock()
	defer fake.resetOffsetMutex.Unlock()
	fake.ResetOffsetStub = nil
	fake.resetOffsetReturns = struct {
		result1 error
	}{result1}
}

func (fake *KafkaOffsetManager) ResetOffsetReturnsOnCall(i int, result1 error) {
	fake.resetOffsetMutex.Lock()
	defer fake.resetOffsetMutex.Unlock()
	fake.ResetOffsetStub = nil
	if fake.resetOffsetReturnsOnCall == nil {
		fake.resetOffsetReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resetOffsetReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *KafkaOffsetManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *KafkaOffsetManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kafka.OffsetManager = new(KafkaOffsetManager)
